### crete category

POST  http://localhost:5000/categorie
Content-Type: application/json

{
    "name" : "buffet",
    "notes" : "this category is fixed to be dejeuner",
    "unit_price" : 400

}

### crete category

GET http://localhost:5000/categorie