### get One User 

POST  http://localhost:5000/auth/signup
Content-Type: application/json

{
    "email" : "derouachi80@gmail.com",
    "password" : "derouachi1998",
    "phone" : "0645264051",
    "adresse" : "15, settat, morrocco",
    "firstName" : "Khalid",
    "familyName" : "derouachi"
}

### signin into 

POST  http://localhost:5000/auth/signin
Content-Type: application/json

{
    "email" : "derouachi80@gmail.com",
    "password" : "derouachi1998"
}

### Get One User
GET  http://localhost:5000/auth/1


### Get All User

GET  http://localhost:5000/auth

### Delete User


### Get All User

GET  http://localhost:5000/auth?role=emp

### Delete User


DELETE  http://localhost:3000/auth/5
 

### Update User

PATCH  http://localhost:3000/auth/1
Content-Type: application/json

{
    "password" :  "Jamal"
}